src/main/java/ru/ermakov/taskmanager/model/Project.java
package ru.ermakov.taskmanager.model;

import org.eclipse.persistence.annotations.CascadeOnDelete;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "app_project")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Project extends AbstractDeal {

    @CascadeOnDelete
    @OneToMany(mappedBy = "project", cascade = CascadeType.REMOVE)
    private List<Task> taskList;

    public Project() {
    }

    public List<Task> getTaskList() {
        return taskList;
    }

    public void setTaskList(List<Task> taskList) {
        this.taskList = taskList;
    }
}

src/main/java/ru/ermakov/taskmanager/model/Task.java
package ru.ermakov.taskmanager.model;

import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cache;

import javax.persistence.*;

@Entity
@Table(name = "app_task")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Task extends AbstractDeal {

    @ManyToOne
    @JoinColumn(name = "projectId")
    private Project project;

    public Task() {
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }
}

src/main/java/ru/ermakov/taskmanager/controller/ProjectController.java
package ru.ermakov.taskmanager.controller;

import org.jetbrains.annotations.Nullable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ru.ermakov.taskmanager.api.service.IProjectService;
import ru.ermakov.taskmanager.enumerate.ReadinessStatus;
import ru.ermakov.taskmanager.dto.ProjectDTO;

import javax.faces.bean.ManagedBean;
import java.util.List;

@Component
@ManagedBean(eager = true)
public class ProjectController {

    @Autowired
    private IProjectService projectService;

    @Nullable
    private ProjectDTO currentProject = new ProjectDTO();

    public void onload(@Nullable final String id) {
        if (id == null || id.isEmpty()) {
            return;
        }
        currentProject = projectService.findById(id);
    }

    @Nullable
    public ProjectDTO getCurrentProject() {
        return currentProject;
    }

    public void setCurrentProject(@Nullable final ProjectDTO currentProject) {
        this.currentProject = currentProject;
    }

    @Nullable
    public ProjectDTO project(@Nullable final String id) {
        if (id == null || id.isEmpty())
            return null;
        return projectService.findById(id);
    }

    @Nullable
    public List<ProjectDTO> list() {
        return projectService.findAll();
    }

    @Nullable
    public String save(@Nullable final ProjectDTO project) {
        projectService.update(project);
        currentProject = null;
        return "pretty:projectList";
    }

    public void delete(@Nullable final ProjectDTO project) {
        if (project == null)
            return;
        projectService.remove(project.getId());
    }

    @Nullable
    public String clear() {
        projectService.removeAll();
        return "pretty:projectList";
    }

    public ReadinessStatus[] getReadinessStatuses() {
        return ReadinessStatus.values();
    }
}

src/main/java/ru/ermakov/taskmanager/controller/TaskController.java
package ru.ermakov.taskmanager.controller;

import org.jetbrains.annotations.Nullable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ru.ermakov.taskmanager.api.service.IProjectService;
import ru.ermakov.taskmanager.api.service.ITaskService;
import ru.ermakov.taskmanager.enumerate.ReadinessStatus;
import ru.ermakov.taskmanager.dto.TaskDTO;

import javax.faces.bean.ManagedBean;
import java.util.List;

@Component
@ManagedBean(eager = true)
public class TaskController {

    @Autowired
    private IProjectService projectService;

    @Autowired
    private ITaskService taskService;

    @Nullable
    private TaskDTO currentTask = new TaskDTO();

    public void onload(@Nullable final String id) {
        if (id == null || id.isEmpty()) {
            return;
        }
        currentTask = taskService.findById(id);
    }

    @Nullable
    public TaskDTO getCurrentTask() {
        return currentTask;
    }

    public void setCurrentTask(@Nullable final TaskDTO currentTask) {
        this.currentTask = currentTask;
    }

    @Nullable
    public TaskDTO task(@Nullable final String id) {
        if (id == null || id.isEmpty())
            return null;
        return taskService.findById(id);
    }

    @Nullable
    public List<TaskDTO> list() {
        return taskService.findAll();
    }

    @Nullable
    public String save(@Nullable final TaskDTO task) {
        taskService.update(task);
        currentTask = null;
        return "pretty:taskList";
    }

    public void delete(@Nullable final TaskDTO task) {
        if (task == null)
            return;
        taskService.remove(task.getId());
    }

    public void clear() {
        taskService.removeAll();
    }

    public ReadinessStatus[] getReadinessStatuses() {
        return ReadinessStatus.values();
    }
}

src/main/webapp/views/projectAdd.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
    <meta name="viewport" content="width=device-width, initial-scale=1" http-equiv="X-UA-Conpatible"/>
    <title>New project</title>

    <f:metadata>
        <f:viewParam name="id" value="id"/>
        <f:viewAction action="#{projectController.onload(null)}"/>
    </f:metadata>
</h:head>
<h:body>
    <h:form>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td width="160" nowrap="nowrap" style="text-align: center">
                    <h3>TASK-MANAGER</h3>
                </td>
                <td width="100%">
                    <p:menubar>
                        <p:submenu label="Project" icon="pi pi-pencil">
                            <p:menuitem value="New" action="pretty:projectAdd" icon="pi pi-briefcase"/>
                            <p:menuitem value="List" action="pretty:projectList" icon="pi pi-briefcase"/>
                            <p:menuitem value="Clear" action="#{projectController.clear()}" icon="pi pi-times"/>
                        </p:submenu>
                        <p:submenu label="Task" icon="pi pi-pencil">
                            <p:menuitem value="New" action="pretty:taskAdd" icon="pi pi-briefcase"/>
                            <p:menuitem value="List" action="pretty:taskList" icon="pi pi-briefcase"/>
                            <p:menuitem value="Clear" action="#{taskController.clear()}" icon="pi pi-times"/>
                        </p:submenu>
                        <f:facet name="options">
                            <p:commandButton type="button" value="Logout" icon="pi pi-home"/>
                        </f:facet>
                    </p:menubar>
                </td>
            </tr>
        </table>
    </h:form>
    <br/>

    <h:form style="margin-left: 1%">
        <table cellpadding="0" cellspacing="0" border="0" style="padding-left: 160px">
            <tr>
                <td width="150" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="projectName" value="Name:"/>
                </td>
                <td>
                    <p:inputText id="projectName" value="#{projectController.currentProject.name}" style="width: 300px"/>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="projectDescription" value="Description:"/>
                </td>
                <td>
                    <p:inputText id="projectDescription" value="#{projectController.currentProject.description}" style="width: 300px"/>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="dateBegin" value="Date begin:"/>
                </td>
                <td>
                    <p:inputText a:type="date" id="dateBegin" value="#{projectController.currentProject.dateBegin}" style="width: 300px">
                        <f:convertDateTime pattern="yyyy-MM-dd"/>
                    </p:inputText>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="dateEnd" value="Date end:"/>
                </td>
                <td>
                    <p:inputText a:type="date" id="dateEnd" value="#{projectController.currentProject.dateEnd}" style="width: 300px">
                        <f:convertDateTime pattern="yyyy-MM-dd"/>
                    </p:inputText>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="projectReadinessStatus" value="Status:"/>
                </td>
                <td>
                    <p:selectOneMenu id="projectReadinessStatus" value="#{projectController.currentProject.readinessStatus}" style="width: 300px">
                        <f:selectItems value="#{projectController.readinessStatuses}" var="status"
                                       itemValue="#{status}" itemLabel="#{status.displayName}"/>
                    </p:selectOneMenu>
                </td>
            </tr>
        </table>
        <br/>

        <table cellpadding="0" cellspacing="0" border="0" style="padding-left: 160px">
            <tr>
                <td>
                    <p:commandButton value="Create" action="#{projectController.save(projectController.currentProject)}"/>
                </td>
                &nbsp;&nbsp;
                <td>
                    <p:commandButton value="Cancel" action="pretty:projectList"/>
                </td>
            </tr>
        </table>
    </h:form>
</h:body>
</html>

src/main/webapp/views/projectEdit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
    <meta name="viewport" content="width=device-width, initial-scale=1" http-equiv="X-UA-Conpatible"/>
    <title>#{projectController.currentProject.name}</title>

    <f:metadata>
        <f:viewParam name="id" value="id"/>
        <f:viewAction action="#{projectController.onload(id)}"/>
    </f:metadata>
</h:head>
<h:body>
    <h:form>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td width="160" nowrap="nowrap" style="text-align: center">
                    <h3>TASK-MANAGER</h3>
                </td>
                <td width="100%">
                    <p:menubar>
                        <p:submenu label="Project" icon="pi pi-pencil">
                            <p:menuitem value="New" action="pretty:projectAdd" icon="pi pi-briefcase"/>
                            <p:menuitem value="List" action="pretty:projectList" icon="pi pi-briefcase"/>
                            <p:menuitem value="Clear" action="#{projectController.clear()}" icon="pi pi-times"/>
                        </p:submenu>
                        <p:submenu label="Task" icon="pi pi-pencil">
                            <p:menuitem value="New" action="pretty:taskAdd" icon="pi pi-briefcase"/>
                            <p:menuitem value="List" action="pretty:taskList" icon="pi pi-briefcase"/>
                            <p:menuitem value="Clear" action="#{taskController.clear()}" icon="pi pi-times"/>
                        </p:submenu>
                        <f:facet name="options">
                            <p:commandButton type="button" value="Logout" icon="pi pi-home"/>
                        </f:facet>
                    </p:menubar>
                </td>
            </tr>
        </table>
    </h:form>
    <br/>

    <h:form style="margin-left: 1%">
        <table cellpadding="0" cellspacing="0" border="0" style="padding-left: 160px">
            <tr>
                <td width="150" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="projectName" value="Name:"/>
                </td>
                <td>
                    <p:inputText id="projectName" value="#{projectController.currentProject.name}" style="width: 300px"/>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="projectDescription" value="Description:"/>
                </td>
                <td>
                    <p:inputText id="projectDescription" value="#{projectController.currentProject.description}" style="width: 300px"/>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="dateBegin" value="Date begin:"/>
                </td>
                <td>
                    <p:inputText a:type="date" id="dateBegin" value="#{projectController.currentProject.dateBegin}" style="width: 300px">
                        <f:convertDateTime pattern="yyyy-MM-dd"/>
                    </p:inputText>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="dateEnd" value="Date end:"/>
                </td>
                <td>
                    <p:inputText a:type="date" id="dateEnd" value="#{projectController.currentProject.dateEnd}" style="width: 300px">
                        <f:convertDateTime pattern="yyyy-MM-dd"/>
                    </p:inputText>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="projectReadinessStatus" value="Status:"/>
                </td>
                <td>
                    <p:selectOneMenu id="projectReadinessStatus" value="#{projectController.currentProject.readinessStatus}" style="width: 300px">
                        <f:selectItems value="#{projectController.readinessStatuses}" var="status"
                                       itemValue="#{status}" itemLabel="#{status.displayName}"/>
                    </p:selectOneMenu>
                </td>
            </tr>
        </table>
        <br/>
        <table cellpadding="0" cellspacing="0" border="0" style="padding-left: 160px">
            <tr>
                <td>
                    <p:commandButton value="Update" action="#{projectController.save(projectController.currentProject)}"/>
                </td>
                &nbsp;&nbsp;
                <td>
                    <p:commandButton value="Cancel" action="pretty:projectList"/>
                </td>
            </tr>
        </table>
    </h:form>
</h:body>
</html>

src/main/webapp/views/projectList.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <meta name="viewport" content="width=device-width, initial-scale=1" http-equiv="X-UA-Conpatible"/>
    <title>Project list</title>
</h:head>
<h:body>
    <h:form>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td width="160" nowrap="nowrap" style="text-align: center">
                    <h3>TASK-MANAGER</h3>
                </td>
                <td width="100%">
                    <p:menubar>
                        <p:submenu label="Project" icon="pi pi-pencil">
                            <p:menuitem value="New" action="pretty:projectAdd" icon="pi pi-briefcase"/>
                            <p:menuitem value="List" action="pretty:projectList" icon="pi pi-briefcase"/>
                            <p:menuitem value="Clear" action="#{projectController.clear()}" icon="pi pi-times"/>
                        </p:submenu>
                        <p:submenu label="Task" icon="pi pi-pencil">
                            <p:menuitem value="New" action="pretty:taskAdd" icon="pi pi-briefcase"/>
                            <p:menuitem value="List" action="pretty:taskList" icon="pi pi-briefcase"/>
                            <p:menuitem value="Clear" action="#{taskController.clear()}" icon="pi pi-times"/>
                        </p:submenu>
                        <f:facet name="options">
                            <p:commandButton type="button" value="Logout" icon="pi pi-home"/>
                        </f:facet>
                    </p:menubar>
                </td>
            </tr>
        </table>
    </h:form>
    <br/>

    <p:dataTable var="project" value="${projectController.list()}"
                 class="table table-striped table-hover table-bordered tableUpdated">
        <p:column headerText="№" style="width: 5%; text-align: center">
            <h:outputText value="#{rowIndex + 1}"/>
        </p:column>

        <p:column headerText="Project name">
            <h:outputText value="#{project.name}"/>
        </p:column>

        <p:column headerText="Project description">
            <h:outputText value="#{project.description}"/>
        </p:column>

        <p:column headerText="Status" style="width: 15%; text-align: center">
            <h:outputText value="#{project.readinessStatus}"/>
        </p:column>

        <p:column headerText="View" style="width: 5%; text-align: center">
            <h:form>
                <h:link value="VIEW" outcome="projectView" includeViewParams="true">
                    <f:param value="#{project.id}" name="id"/>
                </h:link>
            </h:form>
        </p:column>

        <p:column headerText="Edit" style="width: 5%; text-align: center">
            <h:form>
                <h:link value="EDIT" outcome="projectEdit" includeViewParams="true">
                    <f:param value="#{project.id}" name="id"/>
                </h:link>
            </h:form>
        </p:column>

        <p:column headerText="Remove" style="width: 5%; text-align: center">
            <h:form>
                <h:commandLink action="#{projectController.delete(project)}">REMOVE</h:commandLink>
            </h:form>
        </p:column>

    </p:dataTable>
</h:body>
</html>

src/main/webapp/views/projectView.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <meta name="viewport" content="width=device-width, initial-scale=1" http-equiv="X-UA-Conpatible"/>
    <title>#{projectController.currentProject.name}</title>

    <f:metadata>
        <f:viewParam name="id" value="id"/>
        <f:viewAction action="#{projectController.onload(id)}"/>
    </f:metadata>
</h:head>
<h:body>
    <h:form>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td width="160" nowrap="nowrap" style="text-align: center">
                    <h3>TASK-MANAGER</h3>
                </td>
                <td width="100%">
                    <p:menubar>
                        <p:submenu label="Project" icon="pi pi-pencil">
                            <p:menuitem value="New" action="pretty:projectAdd" icon="pi pi-briefcase"/>
                            <p:menuitem value="List" action="pretty:projectList" icon="pi pi-briefcase"/>
                            <p:menuitem value="Clear" action="#{projectController.clear()}" icon="pi pi-times"/>
                        </p:submenu>
                        <p:submenu label="Task" icon="pi pi-pencil">
                            <p:menuitem value="New" action="pretty:taskAdd" icon="pi pi-briefcase"/>
                            <p:menuitem value="List" action="pretty:taskList" icon="pi pi-briefcase"/>
                            <p:menuitem value="Clear" action="#{taskController.clear()}" icon="pi pi-times"/>
                        </p:submenu>
                        <f:facet name="options">
                            <p:commandButton type="button" value="Logout" icon="pi pi-home"/>
                        </f:facet>
                    </p:menubar>
                </td>
            </tr>
        </table>
    </h:form>
    <br/>

    <p:dataTable var="project" value="${projectController.currentProject}"
                 class="table table-striped table-hover table-bordered tableUpdated">
        <p:column headerText="№" style="width: 5%; text-align: center">
            <h:outputText value="#{rowIndex + 1}"/>
        </p:column>

        <p:column headerText="Project name">
            <h:outputText value="#{project.name}"/>
        </p:column>

        <p:column headerText="Project description">
            <h:outputText value="#{project.description}"/>
        </p:column>

        <p:column headerText="Status" style="width: 15%; text-align: center">
            <h:outputText value="#{project.readinessStatus}"/>
        </p:column>

        <p:column headerText="Date begin">
            <h:outputText value="#{project.dateBegin}"/>
        </p:column>

        <p:column headerText="Date end">
            <h:outputText value="#{project.dateEnd}"/>
        </p:column>
    </p:dataTable>
    <br/>

    <table cellpadding="0" cellspacing="0" border="0" style="padding-left: 160px">
        <tr>
            <td>
                <p:commandButton value="Return" action="pretty:projectList"/>
            </td>
        </tr>
    </table>
</h:body>
</html>

src/main/webapp/views/taskAdd.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
    <meta name="viewport" content="width=device-width, initial-scale=1" http-equiv="X-UA-Conpatible"/>
    <title>New task</title>

    <f:metadata>
        <f:viewParam name="id" value="id"/>
        <f:viewAction action="#{taskController.onload(null)}"/>
    </f:metadata>
</h:head>
<h:body>
    <h:form>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td width="160" nowrap="nowrap" style="text-align: center">
                    <h3>TASK-MANAGER</h3>
                </td>
                <td width="100%">
                    <p:menubar>
                        <p:submenu label="Project" icon="pi pi-pencil">
                            <p:menuitem value="New" action="pretty:projectAdd" icon="pi pi-briefcase"/>
                            <p:menuitem value="List" action="pretty:projectList" icon="pi pi-briefcase"/>
                            <p:menuitem value="Clear" action="#{projectController.clear()}" icon="pi pi-times"/>
                        </p:submenu>
                        <p:submenu label="Task" icon="pi pi-pencil">
                            <p:menuitem value="New" action="pretty:taskAdd" icon="pi pi-briefcase"/>
                            <p:menuitem value="List" action="pretty:taskList" icon="pi pi-briefcase"/>
                            <p:menuitem value="Clear" action="#{taskController.clear()}" icon="pi pi-times"/>
                        </p:submenu>
                        <f:facet name="options">
                            <p:commandButton type="button" value="Logout" icon="pi pi-home"/>
                        </f:facet>
                    </p:menubar>
                </td>
            </tr>
        </table>
    </h:form>
    <br/>

    <h:form style="margin-left: 1%">
        <table cellpadding="0" cellspacing="0" border="0" style="padding-left: 160px">
            <tr>
                <td width="150" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="taskName" value="Name:"/>
                </td>
                <td>
                    <p:inputText id="taskName" value="#{taskController.currentTask.name}" style="width: 300px"/>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="taskDescription" value="Description:"/>
                </td>
                <td>
                    <p:inputText id="taskDescription" value="#{taskController.currentTask.description}" style="width: 300px"/>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="projectName" value="Project name:"/>
                </td>
                <td>
                    <p:selectOneMenu id="projectName" value="#{taskController.currentTask.projectId}" style="width: 300px">
                        <f:selectItems value="#{projectController.list()}" var="project"
                                       itemValue="#{project.id}" itemLabel="#{project.name}"/>
                    </p:selectOneMenu>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="dateBegin" value="Date begin:"/>
                </td>
                <td>
                    <p:inputText a:type="date" id="dateBegin" value="#{taskController.currentTask.dateBegin}" style="width: 300px">
                        <f:convertDateTime pattern="yyyy-MM-dd"/>
                    </p:inputText>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="dateEnd" value="Date end:"/>
                </td>
                <td>
                    <p:inputText a:type="date" id="dateEnd" value="#{taskController.currentTask.dateEnd}" style="width: 300px">
                        <f:convertDateTime pattern="yyyy-MM-dd"/>
                    </p:inputText>
                </td>
            </tr>

            <tr>
                <td width="100" height="40" nowrap="nowrap" style="text-align: left">
                    <p:outputLabel for="taskReadinessStatus" value="Status:"/>
                </td>
                <td>
                    <p:selectOneMenu id="taskReadinessStatus" value="#{taskController.currentTask.readinessStatus}" style="width: 300px">
                        <f:selectItems value="#{taskController.readinessStatuses}" var="status"
                                       itemValue="#{status}" itemLabel="#{status.displayName}"/>
                    </p:selectOneMenu>
                </td>
            </tr>
        </table>
        <br/>

        <table cellpadding="0" cellspacing="0" border="0" style="padding-left: 160px">
            <tr>
                <td>
                    <p:commandButton value="Create" action="#{taskController.save(taskController.currentTask)}"/>
                </td>
                &nbsp;&nbsp;
                <td>
                    <p:commandButton value="Cancel" action="pretty:taskList"/>
                </td>
            </tr>
        </table>
    </h:form>
</h:body>
</html>

src/main/webapp/views/taskEdit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <h:outputLabel value="Hello, world"/>
</f:view>
</html>